### ISSUE TITLE
LSTM predictor: add population for regions of Brazil

### ISSUE THREAD

**Issue by ofrancon** [leaf-ai/covid-xprize#124]
Oxford has recently added data for regions of Brazil (see [Brazil sub-national data press release](https://www.bsg.ox.ac.uk/sites/default/files/2020-11/2020-11-25-Brazil-policies-effectiveness-press-release-EN.pdf))

Add regions of Brazil population estimates to the LSTM predictor to let it predict for them.

**Comment by ofrancon** [comment]
We can use population estimates from https://en.wikipedia.org/wiki/States_of_Brazil

**Comment by dsargent** [comment]
Not working -- Brazil states are not showing up in forecasts from pipeline. Also dashboard needs to be updated to add lat-long.
