### ISSUE TITLE
What is $PWD of cron execution?

### ISSUE THREAD

**Issue by jjpr** [leaf-ai/covid-xprize#142]
In the README, it says:  

> Expect that the current working directory will be your sandbox work directory when your script is called. Therefore, references to other modules and resource files should be relative to that.

But my dummy script that works fine from my shell (with `$PWD` as `/home/xprize/work`) fails when run by `cron`:  

`Fatal error: cannot open file 'dummy.R': No such file or directory
`

I'm having trouble figuring out the environment the job launched by `cron` runs in.  What user owns the process, whether any shell dotfiles (`.bashrc` etc.) are run, in general how execution differs from execution from my shell.  I see that `covid-xprize-robotasks-main/judging/scripts/generate_predictions.sh` modifies `PATH` and `PYTHONPATH`.  Are there other useful tidbits we should know?

**Comment by dsargent** [comment]
The cron-like task runs from the home directory, `/home/xprize`. It is run as the xprize user, the same one you are logged on as when you access the sandbox. 

The scripts run by the cron job are located in [this](https://github.com/leaf-ai/covid-xprize-robotasks/tree/main/judging) public repository, which is downloaded to each sandbox as part of the job.

In general the cron-like task's environment is _no_ different than your interactive environment, other than the changes that are visible in the scripts you referenced.

**Comment by jjpr** [comment]
Thank you for the clarification. This helps a lot. I've now successfully used ~/.schedule/run.sh to launch the robojudge system, and am able to reproduce the errors from the nightly logs.
