### ISSUE TITLE
Ground truth missing for Washington DC

### ISSUE THREAD

**Issue by dsargent** [leaf-ai/covid-xprize#164]

**Comment by rbilleci** [comment]
FYI - the ground truth data is also missing for the Virgin Islands

**Comment by ofrancon** [comment]
Ground truth was missing for `Washington DC` and `Virgin Islands` in the leaderboard.
Was fixed by #159
But was not deployed to the robojudge box. 
Deployed and reran robojudge. Leaderboard looks ok now.
